### ISSUE TITLE
[Search restaurants] - Sort and filter options not displaying properly on small screens

### ISSUE THREAD

**Issue by rethramos** [jasonevangelista/stsweng-zarap#36]
Summary:
When viewing the app on small screens (mobile devices), only a portion of the text in the sort and filter options of the search results page can be viewed.

Steps to reproduce:
[https://docs.google.com/document/d/1Uobzm1vLF1DjARixKOqo0aQppo43tGK-UIg8QRxZkME/edit?usp=sharing](https://docs.google.com/document/d/1Uobzm1vLF1DjARixKOqo0aQppo43tGK-UIg8QRxZkME/edit?usp=sharing)

Expected Results:
The full text of the sort and filter options of the search results page should be completely readable.

Actual Results: 
Only the first two characters of the text in the sort and filter options can be seen. The functionality of the buttons is not affected.

More Info:
Source URL: [zarap.vercel.app](zarap.vercel.app)

Specifications  | Description
-- | --
Browser Used | Chrome 87.0.4280.101
Operating System | Android 9
Defect Reported Date | January 14, 2021
Defect Reported Time | 4:00 pm
Status | Initial Submission of Report

**Comment by LouisD69** [comment]
|  
-- | --
Reporter | Team Rocket (Dela Cruz)
Date | Jan 15, 2021
Environment | Windows 10 - Microsoft Edge
Priority level | Low

**Steps to reproduce:** 
1. Using the restaurants search bar in the homepage, search for “Choi Garden”
2. Set the window size to 375 x 667 (recommend using Window Resizer extension in Chrome/Edge, manual resize will also work)

**Expected Result:**
The components of the page will resize in such way that the contents are displayed properly

**Actual Result:**
The components did not resize and display the contents properly.

**Screenshot:**
![image](https://user-images.githubusercontent.com/61369999/104809801-c57b6080-582a-11eb-933a-c13c24b4d2c6.png)
